garris/BackstopJS

- capture/config.default.json
- capture/genBitmaps.js
- compare/index.html
I'm giving a presentation on this tool next week, comparing how simple it is to use compared to a tool like PhantomCSS. I've been including config examples in my slides which means I've been thinking a lot about how to simplify them so the on boarding process on getting up and running is even smoother.
{
"name": "phone",
"viewport":  {"width": 320, "height": 480 }
}
Why wrap the dimensions in another object? Each viewport is already wrapped in the array 'viewports' so it feels like we could simplify the structure here.
{
"name": "phone",
"width": 320, 
"height": 480 
}
"grabConfigs" 
The name of this array is a little nondescript, it would be better if it described the items it contains like the "viewports" array does. How about "pages" or "tests"?
{
"testName":"Home", …
> Simplify the config structure to improve usability

- README.md
- capture/echoFiles.js
- capture/genBitmaps.js
Hi @garris 
This is pull request for https://github.com/garris/BackstopJS/issues/44.
Add patch for capture/echoFiles.js and capture/genBitmaps.js.
If `scenario` has `cookiesJsonFile` property, BackstopJS assumes it as a path of JSON file, reads cookies from the file, and sets cookies to PhantomJS object.
This enables BackstopJS to take screen capture for login-required pages.
Add explanation of `cookiesJsonFile` property to README.md.
It includes short explanation and example contents of `cookiesJsonFile`.
It helps users to learn what it is, and how to deal with it.
> Add `cookiesJsonFile` option

- gulp/tasks/compare.js
This adds the label to the comparison results shown in command line report.
Currently the results are too cryptic to decipher as the filename doesn't contain information to let the user know which page/component is failing/succeeding. (A unique number is used at the beginning of the filename, but that number doesn't intuitively translate into a specific page/component to the user running the test.)
> Adding label to console log compare output.

- README.md
- capture/casper_scripts/onReady.js
- capture/genBitmaps.js
This passes the `viewports` array from `backstop.json` into the `onReadyScript` scripts (i.e. `onReady.js`) so you can do stuff for just a specific viewport like so:
```js
module.exports = function(casper, scenario, vp) {
casper.echo( 'Clicking button' );
casper.click( '.toggle' );
if (vp.name === 'phone') {
// do stuff for just phone viewport here
}
// do other cool stuff here, see Casperjs.org for a full API and many ideas.
// scenario is the current scenario object being run from your backstop.json file
}
```
Thanks for making such a great tool – I'm really loving it so far! :beers:
> Gives Casper scripts Viewport Info

- gulp/tasks/compare.js
Saves diff images of failed diffs in the paths.bitmaps_test/[timestamp]
directory
> Saves image-diffs when using the CLI reporter #121

- README.md
- gulp/tasks/_init_.js
- gulp/util/paths.js
- test/configExample.js
- test/util/paths_spec.js
Feature wanted in https://github.com/garris/BackstopJS/issues/117
Must be used with --backstopConfigFilePath to use a json/js config file.
> Use "require" to load config

- gulp/tasks/compare.js
uses `path.sep` instead of hardcoded platform specific path separators
> fixes #129 avoid platform specific path separator

- capture/echoFiles.js
- capture/genBitmaps.js
- gulp/tasks/bless.js
- gulp/tasks/compare.js
- gulp/tasks/openReport.js
- gulp/tasks/test.js
- gulp/util/genDefaultCompareConfig.js
- gulp/util/updateCompareConfig.js
- package.json
* use npm's checksum to compute file checksums (uses sha1)
* introduces `compareConfig.lastConfigHash` to persist config checksum
* move content of `compareConfig` to `compareConfig.compareConfig`
* makes bless compute a checksum of the config and adding it to the
compareConfigFile as `lastConfigHash`
> #124 uses checksum to detect config changes

- capture/genBitmaps.js
adds the ability to specify global configs for mismatchThreshold and readyEvent. Both configs can be overridden by specifying either readyEvent or mismatchThreshold on a scenario level
> #127 global config for misMatchThreshold/readyEvent

- gulp/tasks/test.js
Currently the tests don't work on a fresh checkout (if no
`paths.compareConfigFileName` exists). The check whether a config has
been changed should only fail if a compareConfig exists and
contains a different checksum than the `paths.activeCaptureConfigPath`'s
checksum
> #124 makes sure tests work on fresh workspace

- capture/genBitmaps.js
When running the reference, updating the echos so they don't assume scenario.url, per the discussion in #140
> Updating reference echo message

- gulp/tasks/compare.js
Make the CLI report a little prettier.
- Added red and green to error and passes. 
- Removed extra space. 
- Standardized on single quotes inside console.log.
> Add console log colors

- compare/css/styles.css
- compare/index.html
Use flexbox to size column widths on the BackstopJS report.
Previously, using a table with 4 columns at 25% width didn't always results in equal columns.
This meant that the diff image would not necessarily line up with the reference and test images meaning it was difficult on long pages to easily eyeball the identified differences with the reference and test images.
Using flexbox means that we can guarantee that the columns will be of equal width, and hence the images will line up properly.
> Use flexbox to size column widths on the BackstopJS report

- compare/css/styles.css
This pull request fixes a small problem with flexbox display in Firefox, whereby large images are not constrained to their container correctly.
Tested on the latest release of all major browsers (Edge 13, IE 11, FF 46, Chrome 49).
Note that Flexbox support is pretty good these days, but IE9 and before are not supported:
http://caniuse.com/#feat=flexbox
> Fix flexbox display for Firefox

- README.md
it isn't immediately obvious that it's necessary to include a wait inside custom scripts for any page state changes to be included in the screenshots, so I'd suggest including this in the example
> include wait in example custom casper script

- gulp/tasks/compare.js
- gulp/util/paths.js
- package.json
The regression test report will be generated in the JUnit format and report will be placed in the given directory (default: _[backstopjs dir]/test/ci_report/xunit.xml_).
The following config would enable the CI - report (default: junit format)
```
report : [ CLI ,  CI ],
```
The following optional config would override the default config
```
paths : {
bitmaps_reference :  ../../tests/bitmaps_reference ,
bitmaps_test :  ../../tests/bitmaps_test ,
compare_data :  ../../tests/bitmaps_reference/compare.json ,
~      casper_scripts :  ../../tests/casper_scripts ,
+      ci_report :  ../../tests/ci_report
+   },
+    ci : {
+      format :  junit ,
+      testSuiteName :  backstopJS
+
},
```
> adding JUnit report generation functionality

- README.md
- capture/genBitmaps.js
When using a "body" selector, the capture is clipped to the area of the viewport.
Using `casper.capture()` you can capture the entire document regardless of size.
> prevent clipping when using "body" selector

- gulp/tasks/compare.js
The custom testSuiteName does not work and it's always taking the default name which is 'BackstopJS'. This would fix and make it work as expected.
> custom testSuiteName fix

- gulp/tasks/compare.js
The ```compareConfig.testPairs``` would always be an Object and not an Array. This would fix the https://github.com/garris/BackstopJS/issues/210
> fixing the CI report for mutiple CSS selectors

- gulp/tasks/compare.js
- test/simpleReactApp/backstop.json
Fixes #135.  This PR removes the `cliExitOnFail` option, always exiting code 1 on fail instead:
Exit code is `0`.
```sh
$ npm run test
...
Test completed...
0 Passed
45 Failed
*** Mismatch errors found ***
For a detailed report run `npm run openReport`
[10:48:37] 'compare' errored after 21 s
[10:48:37] Error: Mismatch errors found.
at updateProgress (XXX/node_modules/backstopjs/gulp/tasks/compare.js:30:22)
at Array.<anonymous> (XXX/node_modules/backstopjs/gulp/tasks/compare.js:76:13)
at triggerDataUpdate (XXX/node_modules/node-resemble-js/resemble.js:69:28)
at onceWeHaveBoth (XXX/node_modules/node-resemble-js/resemble.js:447:6)
at .<anonymous> (XXX/node_modules/node-resemble-js/resemble.js:125:13)
at emitOne (events.js:96:13)
at emit (events.js:188:7)
at .<anonymous> …
```
> Exit code 1 on fail

- README.md
- gulp/tasks/compare.js
- gulp/util/paths.js
If there are other test files in the same build test directory, this common name (xunit.xml) may conflict with others. So lets give an option to customize the test report filename.
> Custom Test Report filename

- gulp/util/paths.js
When i installed BackstopJs in my linux server, i want to usr my linux server domain url as the report url so that when i click the console output, i can directly redirect to the compare server.
> support config opening report domain url

- package.json
I'm not quite sure if this works 100% because tests seem a little strange to say the least? In the freshly cloned repo, tests do not run because it tries to execute them in the directory of the user instead of the repo. I managed to run the tests after I commented out the "legacy mode" stuff, that prevents running tests in the repo (for whatever reason?). However after hacking the legacy mode stuff and updating the `node-resemble-js` package I was able to run `npm test` and it succeded (with mismatch errors).
I also tested the functionality in one of my projects (creating references and testing succeeded) - so I'm somewhat confident that this should work.
> Update node-resemble-js package to the latest version, this fixes #316

- core/util/compare.js
Shows either `(dimensions mismatch)` or `(5% / 3%)` - reads as `five percent mismatch on a three percent threshold`.
Fix #306 , Helps #313
> more detailed report why a comparison failed.

- capture/genBitmaps.js
I just upgraded to v2 and noticed that [my previous PR code](https://github.com/garris/BackstopJS/pull/246) to pass isReference to onReadyScript and onBeforeScript is gone.
> Pass isReference flag to onReadyScript and onBeforeScript

- core/util/findExecutable.js
- test/core/util/findExecutable_spec.js
While npm uses the following structure for the bin section (which is the relevant part for this issue)
```json
{
"bin": {
"casperjs": "./bin/casperjs"
},
}
```
Yarn uses the another structure
```json
{
"bin": "./bin/casperjs"
}
```
> fixes #323 compability for executable modules installed with yarn

- capture/genBitmaps.js
- core/command/report.js
- core/util/extendConfig.js
- core/util/makeConfig.js
- core/util/runCasper.js
- package.json
Avoid writing to node_modules/backstopjs/
Added hashed config file creation in tmp folder.
--testReportFileName parameter is added for customized xunit filenames.
Few eslint warnings are fixed.
> Concurrency support with custom xunit filenames

- capture/genBitmaps.js
- core/util/compare.js
- package.json
For saving bandwidth and space especially with huge test cases and CI tool integrations. 
added suggested changes from @garris
> added jpg support.

- core/util/extendConfig.js
`config.openReport` flag was not working as extend config was always setting it to true.
It now uses the value provided in the config file.
> fixes config.openReport flag

- capture/genBitmaps.js
- cli/index.js
- core/command/report.js
- core/util/allSettled.js
- core/util/compare.js
- package.json
Hi @garris,
I tried to update backstop and got a few surprises.
- When an error was thrown in `compareImage` not a single report was shown. (just stopped the process with an exit code of 0)
- Variants were not compared to the base reference image, but to a reference image that was never generated
So I made the following bugfixes for more robust error handling : 
- Centrally catch and log the unhandled errors
- use `allSettled` for report handling, that gives a change for a report to fail and give feedback on that error
- use `p-map` instead of `bluebird.map` because bluebird swallowed errors
- return errors in `compareImage` as `resolve(new Error(...)` so that we can accurately report all errors in image comparisons.
Other changes
- fix a typo in `core/command/report` for …
> Various bugfixes

- capture/genBitmaps.js
Based on https://github.com/garris/BackstopJS/issues/127 this commit adds the possibility to set the threshold to exactly 0.
At the moment this is impossible because of the way the parameter is read from the scenario or config.
> fixes 0 not being recognized as misMatchThreshold value

- README.md
- compare/css/styles.css
- compare/index.html
- core/command/approve.js
- core/command/index.js
- core/util/fs.js
- package.json
`backstop approve` will copy bitmaps from your latest test into your reference directory.  Subsequent tests will be compared against your updated reference files.
Provides a straightforward way to approve changes.
I could also see adding `--filter=<scenario.label || selector>` and `-d` (dry run) arguments to enable approving a more narrow selection.
> New updated workflow feature: backstop approve

- README.md
Updates the README references of `--configPath` to `--config` as the correct way to set a custom config file.
The current documentation fails when the command is run through an NPM script or as a Docker command as references to `--configPath` are superseded by `--config` which is set to `backstop.json` by default in these circumstances.
Fixes: #428
> docs: Update references to configPath

- compare/index.html
I was trying to use symbols in my scenario labels, but they were coming out garbled because the browser wasn't interpreting it as UTF-8.  This adds a meta tag to make the compare report UTF-8 so they render correctly.
> Set compare html charset to UTF-8

- capture/genBitmaps.js
This will set each cookie to its relevant scenario right before its run, rather than setting all of the cookies at the start of the casper instance. The upshot to this is that we'll be able to set custom cookies for any specific scenario!
> Add cookies to bitmaps right before each scenario has run

- core/util/runChromy.js
Avoids error on run.
Sorts https://github.com/garris/BackstopJS/issues/483
> update getMismatchThreshold to pass config

- core/util/BackstopException.js
- core/util/runChromy.js
Hi!
Chromy errors are not rethrown correctly. i.E. if I call chromy.wait with an invalid selector in a scenario, my console only prints "(node:86933) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TimeoutError: timeout", but I can neither catch the error (because it is not rethrown properly) nor find additional information (like scenario or label). Since a timeout occures > 30 seconds asynchronously and I have hundreds of tests running at once, I have no idea what went wrong and am pretty much lost.
This commit adds a nice error that bubbles up so that an outer application may react. If no outer catch exists scenario and viewport details are shown in the console so the user knows where to look for the mistake.
> Chromy: Prevent uncaught errors and make them available for the parent application

- backstop_data/engine_scripts/goToNextPage.js
- capture/backstopTools.js
- core/util/runChromy.js
Solves #541.
I would be glad if somebody could enlighten me why this works. 
Using chromy's `inject` method resulted in no joy at all. Don't get why. Worked in other cases for me.
Trying to do this via `chromy.on('Page.loadEventFired')...` also didn't work.
I guess because the first evaluations are using these methods before this event?
> Inject backstopTools

- docker/Dockerfile
- docker/README.md
- docker/xvfb-run
This PR is for the official BackstopJS Docker image (courtesy of https://github.com/docksal/backstopjs)
The image is self-contained and comes will all dependencies packaged inside it.
Features:
- [BackstopJS 3.x](https://github.com/garris/BackstopJS)
- [PhantomJS](http://phantomjs.org/)
- [SlimerJS](https://slimerjs.org/) (with Firefox ESR)
- [CasperJS](http://casperjs.org/)
- Chromium
Article on the topic: [Visual Regression Testing with BackstopJS in a Docker container](https://blog.docksal.io/visual-regression-testing-with-backstopjs-in-a-docker-container-dfd1b9ae8582)
> BackstopJS Docker image

- README.md
- cli/index.js
- core/util/runChromy.js
Setting an engine parameter value with engineOptions will override any default value set by backstop. 
- (TLDR) Setting `port` is _very_ _very_ not advised.
- Setting `chromeFlags` will override all chromeFlags properties set by backstop -- **EXCEPT FOR `--window-size`***...  (i.e. `--window-size` flag will be added by backstop if not found in chromeFlags) 
- Setting `--window-size` explicitly in `chromeFlags` will override values used in your viewport settings.
> Engine options update

- core/util/compare/index.js
`content` is undefiened in cli report.
>   compare | ERROR { requireSameDimensions: true, size: isDifferent, content: undefined%, threshold: 0.1% }: 
fixed in this pull request.
> fix show misMatchPercentage

- README.md
- core/command/index.js
- core/util/runChromy.js
- Access to static chromy reference in onBefore/onReady scripts. Example usage in README.md.
- Core: Always log out error messages.
Related to: https://github.com/garris/BackstopJS/issues/608
> Access to static Chromy functions

- README.md
- core/util/compare/compare-resemble.js
- examples/simpleReactApp/assets/css/styles.css
- examples/simpleReactApp/backstop.json
- examples/simpleReactApp/package.json
- examples/simpleReactApp/readme.md
Hi, 
I would like an option to ignore antialiasing. In resemble it is possible by 
`resemble().compareTo().ignoreAntialiasing()`. So i've added the configuration to the `resembleOutputOptions` in backstop.json.
Also I updated the react-example to feature this option. Would you be ok with merging and possibly releasing?
Thanks for great tool!
> Add option to use resemble`s ignoreAntialiasing()

- README.md
Just one way we could integrate the PowerShell command. 
Feel free to change if you'd prefer different formatting or wording.
> Add PowerShell cmd to kill headless chrome instances

- docker/Dockerfile
I wanted to use Chrome and the latest version of BackstopJS using Docker. However the automatic build of BackstopJS isn't working.
This PR fixes the docker build error and updates PhantomJS and Chrome. In order to run on the latest stable Chrome 64 build, I had to change the original alpine base image to the default node image. This potentially fixies the memory leak issues reported in #603 #537 
You can test it out on: https://hub.docker.com/r/iain17/backstopjs/
> Fixing Docker build issues. Updated chrome, Potentially fixing issues #603 #537.

- core/util/runPuppet.js
This refers mostly to
https://github.com/GoogleChrome/puppeteer/issues/2161 which I can not
solve unless I pass --no-sandbox and --disable-setuid-sandbox to
puppeteer.
The correct syntax for the backstop.json config would then be (specifically for my use case, as an example):
`"engine": "puppet",`
`"puppeteerArgs": {args: ['--no-sandbox', '--disable-setuid-sandbox']},`
> Adds option to pass additional args to puppeteer.

- package.json
Moves react to peer dependency to prevent hard link and multiple react version installs.
> Adding peerDependencies for react

- package-lock.json
- package.json
Moves react to peer dependency to prevent hard link and multiple react version installs.
Local development supported by adding dev dependency on react and react-dom.
> Adding peer dependencies and dev dependencies for react and react-dom

- compare/src/components/App.js
- compare/src/reducers/scrubber.js
- core/util/runPuppet.js
- docker/Dockerfile
- package-lock.json
- package.json
Details of the issue can be found in this issue https://github.com/garris/BackstopJS/issues/704
Ran lint which produced two changes that only add an empty spaces ... meh.
My change is tiny and is to do with the way we use puppeteer to make screenshots of specific elements on a page. So instead of using the element.screenshot() function to directly take a screenshot of the selected element, I have used page.screenshot() and provided the boundingBox object of the element as reference for the location of the element on the page. For some reason this way produces the expected screenshots. I am surprised it doesn't just work the way it was implemented, because in puppeteer's API documentation they claim that element.screenshot() essentially uses page.screenshot underneath ... weird.
@garris I …
> Puppeteer fix for creating blank (off page) screenshots

- README.md
In the integration example the required var name is `backstopjs`, but in 2 other locations in the readme it's `backstop`. This change will make the naming consistent, since there's no reason for the difference.
> Readme - consistently name the example of required backstop

- core/util/runPuppet.js
selectorShot: pass correct variable to fs.copy
Fixes #810
> fix fallback images in puppeteer (#810)

- docker/README.md
Need to change the `pwd` command to `pwd -W` to work on windows (when using git bash).
> docs(readme): add windows instructions

- CONTRIBUTING.md
- core/command/reference.js
- core/command/test.js
- core/util/runDocker.js
- `backstop test --docker` was actually running `reference` instead. Fixed that and did a bit of refactoring so there's less copied and pasted code. 
- If you have spaces in a command it now adds quotes around it when passing through to Docker. E.g. `backstop test --docker --filter="some test"`.
- Now `--docker` will work on window as I'm using `${process.cwd()}` instead of `$(pwd)` in the docker command.
- Also added a `CONTRIBUTING.md` guide. It's a start. I couldn't figure out what commands to run and such to test my changes. Had to dig through the `package.json > scripts`. I think it could help others too.
> Fix test command when using docker

- core/util/makeConfig.js
Instead, allow error to bubble up. End result is the same when running via CLI, but when running in another process you don't want to force exit.
> Don't force exit on makeConfig errors

- compare/webpack.config.js
- package-lock.json
- package.json
`npm audit` reports 15 vulnerabilities related to webpack dependencies.
| Before             |  After |
:-------------------------:|:-------------------------:
`npm run build-and-copy-report-bundle` and `npm run smoke-test`, are working as expected.
> Bump dependencies: webpack 4

- package-lock.json
- package.json
This is the last minor bump from `devDependencies`.
Next bump in the list: `eslint` 🔥
> Bump dependencies: prettier

- docker/Dockerfile
- Fixes https://github.com/garris/BackstopJS/issues/932.
- Installs additional font libraries for wide-ranging multilingual support.
Example:
> Fixes #932: Adds CJK language support.

- README.md
- core/command/report.js
- core/util/Reporter.js
- core/util/extendConfig.js
- core/util/fs.js
- test/configs/backstop_features.js
- test/core/command/report_spec.js
- test/core/util/makeConfig_it_spec.js
- Added the ability to create a Json report type. 
My team use the `html_report.config.js` to extract the failed tests and rerun the test suite passing in the failed test labels as `filter` values. eg `backstop test --config=<config> '--filter=<labels>`
This eliminates flakey tests which happen in our CI platform for resource issues. 
Creating a JSON report would mean we wouldn't have to remove the `report()` text in the `html_report.config.js` making the retry code much cleaner.
Also providing a JSON file means we're not likely to encounter breaking changes, as evaluating text output in the `html_report.config.js` is not very reliable.
> Added a json report type

- core/command/test.js
This simple logic change alters the docker branch of `backstop test` so it performs the same config check that `report.js` performs before calling `_openReport`.
As-is, when run via docker, the report is _always_ opened, no matter how the config is set.
> openReport config checked when running 'test' via docker

- README.md
I am adding a notification board section near the top of the readme file to inform users of the repo what is currently going on with the latest build. I was quite confused myself when I ran backstop this morning to find out that Chrome was not running anymore. I had to go through closed pull requests and commits to find out what caused the issue, which is a bit tedious. I think this space could be useful.
P.S. I put in the last version of backstop that worked for me but if there is a later stable version please update @garris
> Notification board in the README file

- core/util/runChromy.js
- core/util/runPuppet.js
I added !important to display none to remove elements really. It is necessary because the selected elements can have styles with important too, for example in Bootstrap the d-* helpers:
`<div class="d-flex">I want to be a flex element</div>`
```
.d-flex {
display: -webkit-box!important;
display: -webkit-flex!important;
display: -moz-box!important;
display: -ms-flexbox!important;
display: flex!important;
}
```
> Fix removeSelectors bug

- package.json
While working on https://github.com/garris/BackstopJS/pull/1079 I noticed that `approve` is the only backstop command that is not exposed in "scripts".
I thought that maybe it's an oversight, so I'm adding it
> Add approve to list of scripts

- core/util/runDocker.js
This is a fix to an issue introduced by #988 
Reproduction of issue:
```
const backstop = require('backstopjs');
/* ... */
backstop('test', { docker: true, config: 'some/path' })
/* ... */
```
Running with docker and any configuration will fail due to the current code attempting to join promises. Simplified error message that is produced (note `[object Promise]` in the end):
```
Error: docker run --rm -it --mount type=bind,source="some/path",target=/src backstopjs/backstopjs:4.3.2 test [object Promise] [object Promise] returned 1
```
> Resolve promises for docker arguments

- core/util/createBitmaps.js
Consider the following configuration:
```javascript
const defaultViewports = [
{
label: 'sm',
...
},
{
label: 'md',
...
},
{
label: 'xl',
...
},
];
const backstopConfig = {
viewports: defaultViewports,
scenarios: [
{
label: 'scenario A',
...
},
{
label: 'scenario B (only runs on xl viewport)',
viewports: defaultViewports.filter(viewport => viewport.label === 'xl'),
...
},
{
label: 'scenario C',
...
},
],
...
};
```
Given that the viewport index is saved in the viewport object itself, in the previous example, both 'sm' and 'xl' will always have the index 0, because the `scenario B` viewports config will override the global 'xl' index.
With this PR, it's created a copy of each viewport configuration, making possible to reuse viewports configuration with predictable viewports indexes.
> Copy viewport objects

- cli/index.js
- core/util/runDocker.js
- test/configs/backstop_alt.js
- test/configs/runFromNode.js
- test/core/util/runDocker_spec.js
Hello, here is the fix for #1113 :smiley: 
The fix itself is one line in `core/util/runDocker.js`.
I also added some tests and fixed some related code.
> fix #1113 `filter: undefined` option is passed as `--filter=undefined` when run with Docker

- cli/index.js
- test/cli/index_spec.js
Fix #1006 
Refactor because process.exit is not recommended
https://stackoverflow.com/questions/5266152/how-to-exit-in-node-js/37592669#37592669
Also added a test to check exit code
> refactor(cli): do not process.exit() + fix cli test

- package-lock.json
- package.json
👋 - I'd like to test the dark mode of the TypeScript website https://github.com/microsoft/TypeScript-Website/pull/187 - to do that I need an API which was added in puppeteer 2.0
It's [puppeteer v2](https://github.com/puppeteer/puppeteer/releases) because it drops node 6 support:
> Puppeteer now requires Node.js v8+; Node.js v6 is no longer supported
I couldn't find a note in the docs about what versions you support for Node, so it's really your call on whether this is a big enough change to warrant a backstop major version. Doesn't seem to be an API changes but maybe the Chrome upgrade could introduce rendering diffs.
> Bumps pupeteer to v2

- core/util/runPuppet.js
Function 'setViewport' is async. So, we have to write await before call async function.
This bug causes errors with actions on resized pages. Espiecially on smaller screens on phone.
> Fix ugly bug with setViewport function

- package-lock.json
- package.json
As a followup to #1180 - this fixes all of the other `npm audit fix` run locally except for the breaking changes/manual verification needed; will defer to devs with more knowledge on the project for the last few.
Most of these fixes are in the package-lock.json transitive dependencies, autoupdated via `npm audit fix` which auto-applies updates if no semver major breakage or otherwise marked for manual upgrades.
Feel free to ignore if you have another process for dependency updating; just wanted to send over as I noticed it.
I can smoke-test-docker, smoke-test and unit-tests (still couldn't get integration-tests to run)
> npm audit fix - but none that require manual intervention

- README.md
I've been teaching about test automation on Udemy, and I thought it would be nice to list my course about visual regression testing with BackstopJS in the tutorials section of the tool's doc.
@garris, would you mind reviewing it, please?
> Add online course on tutorial section

- core/command/remote.js
- remote/index.js
Backstop already supports config to use interactive mode but it was not passed on to backstop remote.
**Changes include:**
- Ability to switch between reference and test modes in backstop remote
- Enable option to use interactive mode in backstop remote
> Using interactive mode and reference mode in backstop remote

- remote/index.js
This PR addresses some comments(from https://github.com/garris/BackstopJS/pull/1216) around handling some edge cases in a better way.
**Changes:**
* better handling of boolean flag - incremental flag
* stricter check for `/dtest` based on which reference or test modes are selected.
_P.S: Tested against _ember-backstop-tutorial_ repo._
> Improve handling edge cases

- README.md
The indentation of the "HTML report development" section was mixing tabs and spaces which caused list level issues. That made the text harder to understand.
This PR fixes it.
Before:
After:
> Fix readme indentation

- compare/webpack.config.js
This PR will add `mode: 'production'` to the webpack config.
Since it is the default nothing should break.
> add mode to webpack config

- README.md
In `npm run lint --fix`, the argument  `--fix` is ignored, we should add `--` before it to get it passed to the actual eslint command. See:
https://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script
> Fix lint command in readme

- README.md
I didn't see the JS config file option. Would consider it misplaced. Added an example.  
I would prefere a automatically picked up YML file, but technically this closes my question in  #1254
> Improve documentation for config file

- core/util/runPuppet.js
Enabling `mergeImgHack` was resulting in whitespace being produced for all but the first screenshot. To resolve this I discovered that the page needed to be scrolled to the appropriate part of the page for the screen.
It's not entirely clear to me why this is needed, I did a lot of exploring in the debug browser window to figure out if there was a better solution but I couldn't find anything although I'm sure there must be.
For comparison here is a before & after capture of netflix's homepage:
| Master      | This branch |
| ----------- | ----------- |
| ![netflixcom_desktop-old](https://user-images.githubusercontent.com/117200/103887979-debe3780-50db-11eb-972a-a70400e7f3d1.png)      | ![netflixcom_desktop](https://user-images.githubusercontent.com/117200/103887994-e2ea5500-50db-11eb-9272- …
> Fix issue with mergeImgHack resulting in whitespace

- capture/engine_scripts/puppet/loadCookies.js
- examples/Jenkins/Sample/backstop_data/engine_scripts/puppet/loadCookies.js
- examples/responsiveDemo/backstop_data/engine_scripts/puppet/loadCookies.js
By testing localhost mostly there is no https connection.
To be able to set it and prevent double http in the url a check was added.
> feat(loadCookies): check for http and https in cookie domain

- README.md
The first argument is the page object, not the engine.
https://github.com/garris/BackstopJS/blob/9e2ecf7dd5b623195b10af987555c68ef668412a/core/util/runPuppet.js#L110
> fix(docs): onBefore / onReady arguments

- capture/engine_scripts/puppet/clickAndHoverHelper.js
- core/util/runPuppet.js
- examples/Jenkins/Sample/backstop_data/engine_scripts/puppet/clickAndHoverHelper.js
- examples/responsiveDemo/backstop_data/engine_scripts/puppet/clickAndHoverHelper.js
- test/configs/backstop_data/engine_scripts/puppet/clickAndHoverHelper.js
> waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
Fixes #1276
> refactor(waitFor): replaced .waitFor by its successor .waitForTimeout

- README.md
- core/util/runPuppet.js
- package-lock.json
- package.json
removes package 'merge-img' and all related code due to recent security issues while 'npm audit'
For detail see #1219 
BTW
I know at this stage 'npm audit' still 'fails' due to other high vulnerabilities in other packages.
Just wanted to keep things separated and may start another PR.
> removes package 'merge-img'

- package-lock.json
- package.json
- use current puppeteer version
- breaking changes introduced in puppeteer v6 or v7 do not affect BackstopJS
- tests successful
> feat(build): Upgrade to puppeteer@7.1.0

- remote/index.js
Instead of using a hardcoded (default) path for the report,
use the path set in the backstop config. This allows custom paths.
> feat(remote): use report paths from config

- package-lock.json
- package.json
- move to `dependency` to remove the requirement to install `puppeteer` for backstopjs separetely and potentially breaking the current setup for users
fix error in #1284
> bugfix(build): fix `puppeteer` as a required dependency

- core/util/runPuppet.js
page.waitFor is deprecated and should be replaces with page.waitForSelector or page.waitForTimeout
Removes warning 
```
waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
```
> page.waitFor is deprecated

- README.md
Hi, @garris,
Here's a small contribution.
A student had doubts about the usage of `hoverSelector`, then I went to the docs and noticed this small typo on `postInteractionWait`'s comment. 😉 
👋🏻
> Fix typo on readme file

- core/util/compare/compare-resemble.js
- package-lock.json
- package.json
Switching `node-resemble-js` to `@mirzazeyrek/node-resemble-js` as discussed in #350 so we can get `pngjs` 6.0 which fixes a crash.
> Switch to maintained resemble.js

- compare/output/index.html
Reason: 
We set it to no cache in the report, because on github pages we don't have control over the caching strategy. 
Caching here is not needed. 
https://github.com/garris/BackstopJS/issues/1352
> - Disable Cache on client side

- capture/engine_scripts/puppet/interceptImages.js
The imageStub.jpg file is only one folder back from the interceptImages.js file. So, I removed the extra `../` so that it can reference the image.
Verified this resolved the Puppeteer ENOENT error message, and Backstop is successfully stubbing images on my computer now.
> Fixed Puppeteer ENOENT Error When Image Stubbing

- docker/Dockerfile
I built this locally and my project's tests still run using the built image after the upgrade.
Is there any other testing you would want doing on this?
It does include an upgrade to a new version of Debian as the node 16 image uses a new major release .
> Update to latest node LTS: 16.14.0

- package-lock.json
- package.json
The version of puppeteer currently bundled with Backstop depends on a vulnerable version of node-fetch. This PR bumps the version of puppeteer to the latest one to get rid of the vulnerability.
I am not sure if the smoke tests are working correctly for me. After cloning the repo without making any changes I already get 32 failed tests with smoke-test-docker. For some of them, it is obvious that they can't work, since the reference images don't have "Playwright" in the first paragraph. Many other tests fail with diff-y plus or minus 1.
At least the results didn't change after I updated puppeteer. I attached the report from smoke-test-docker to this PR: [BackstopJS Report.pdf](https://github.com/garris/BackstopJS/files/8309445/BackstopJS.Report.pdf)
> chore: update puppeteer from 12.0.1 to 13.5.1

- package-lock.json
- package.json
Thank you for merging https://github.com/garris/BackstopJS/pull/1403. This PR includes another dependency update that would be much appreciated.
In one of my projects I use playwright for my E2E tests and as an engine in backstop. With the latest release of playwright the version difference between 1.20 (the latest) and the bundled backstop version (1.17.1) seems to be too large. After using playwright 1.20 to install the browsers, backstops playwright 1.17.1 can't find them.
I tried out this PR in my project and it resolves this issue.
> chore: update playwright from 1.17.1 to 1.20.0

- compare/output/index.html
not needed for HTML5 documents
> remove  type="text/javascript" from reports

- core/util/runPlaywright.js
Pass the browserContext instead of the browser instance.  See comment https://github.com/garris/BackstopJS/pull/1417#issuecomment-1121303500
> Quick fix for early disposal of playwright browser

- core/command/remote.js
Remote command doesn't work anymore on Windows after the PR #1439
Indeed, we can't use same code to add env variables to command on Linux and Windows.
So using the exec command env option.
> Remote command : compatibility with Windows

- capture/engine_scripts/puppet/clickAndHoverHelper.js
- examples/Jenkins/Sample/backstop_data/engine_scripts/puppet/clickAndHoverHelper.js
- examples/responsiveDemo/backstop_data/engine_scripts/puppet/clickAndHoverHelper.js
- test/configs/backstop_data/engine_scripts/puppet/clickAndHoverHelper.js
Puppeteer deprecated and by now, removed `page.waitFor()` (see puppeteer/puppeteer#6214). This results in `TypeError: page.waitFor is not a function` when using things like `postInteractionWait`, `clickSelector` and similar features relying on `clickAndHoverHelper.js`. See #1431 for details.
You can observe this issue when running `npm run smoke-test`:
This PR fixes all usage of `waitFor` in examples, tests and templates used for `backstop init`. 
Projects that ran `backstop init` would still need to change their version of the scripts themselves but at least for new usages, this issue would be fixed (and existing users would have a guide what a fixed version would look like)
(by the way, it's Hacktoberfest so consider opting in by [adding a `hacktoberfest` topic to the …
> Remove usage of deprecated/removed waitFor in clickAndHoverHelper scripts

- README.md
- core/command/remote.js
- core/util/runPlaywright.js
- core/util/runPuppet.js
- examples/responsiveDemo/backstop_data/engine_scripts/puppet/ignoreCSP.js
This PR will introduce a new option for both scenarios or the general `engineOptions` parameter.
It will allow users to modify both Puppeteer and Playwright parameters on `page.goto(url, parameters)`.
1. Modify general engine options
```json
"engineOptions": {
"gotoParameters": { "waitUntil": "networkidle0" },
}
```
2. Modify engine options for a single scenario
```json
"scenarios": [
{
"label": "domcontentloaded",
"url": "https://example.com"
"gotoParameters": { "waitUntil": "domcontentloaded" },
}
]
```
I've noticed that the default `waitUntil` parameter for Playwright which is the `load` value is not enough when BackstopJS is creating images for my website. In order to fix it I had to create a patch. I'd like to add it to the core as my piece of contribution. 
This PR also fixes some …
> Allow to modify  `gotoParameters`

- README.md
- core/util/runDocker.js
npm run sanity-test-docker
npm run smoke-test-docker
both are able to run now without permission problems.
> fix permission problem with local bind mount (#1466)

- README.md
- core/util/runDocker.js
- docker/Dockerfile
- defaults to root now again
- added a recommendation to the README.md to configure a more appropriate user to run the test by changing the dockerCommandTemplate config option
- fixes (#1466)
> Rollback docker user change

- core/command/remote.js
closes #1446 
`child_process.exec` isn't aware of the `node` executable path without explicitly including the parent process's `PATH`
Also added logging for `exec` so errors are a little easier to access by downstream users.
_Note: this is likely only for local, `npm i -D backstopjs`, use cases._
> fix(remote): updates `child_process.exec` to include PATH and log errors

- .github/workflows/_backstop-docker-ci.yml
- .github/workflows/backstop-integration-test.yml
- .github/workflows/backstop-sanity-test.yml
- .github/workflows/backstop-smoke-test.yml
- .github/workflows/docker-build.yml
- .github/workflows/docker-sanity-test.yml
- .github/workflows/docker-smoke-test.yml
- .github/workflows/test-backstop.yml
- .github/workflows/test-docker.yml
In a separate branch, I created some GitHub actions and workflows. Happy to submit a PR with those changes as well. And do a walkthrough if you're curious :)
- [![Backstop Tests](https://github.com/dgrebb/BackstopJS/actions/workflows/test-backstop.yml/badge.svg)](https://github.com/dgrebb/BackstopJS/actions/workflows/test-backstop.yml)
- [![Backstop Integration Tests](https://github.com/dgrebb/BackstopJS/actions/workflows/backstop-integration-test.yml/badge.svg)](https://github.com/dgrebb/BackstopJS/actions/workflows/backstop-integration-test.yml)
- [![Backstop Sanity Tests](https://github.com/dgrebb/BackstopJS/actions/workflows/backstop-sanity-test.yml/badge.svg)](https://github.com/dgrebb/BackstopJS/actions/workflows/backstop-sanity-test.yml)
- [![Backstop Smoke …
> ci(github): adds github workflows for CI/CD (#44)

- .github/workflows/_backstop-docker-ci.yml
@garris slight adjustment for GH action on PR - this should allow PRs to run and pull in the corresponding downstream branch properly.
I'll submit a PR with the `headless: new` change in a bit.
Thanks!
> ci(github): checks out head from  for PRs actions

- .github/workflows/_backstop-docker-ci.yml
- .github/workflows/backstop-integration-test.yml
- .github/workflows/backstop-sanity-test.yml
- .github/workflows/backstop-smoke-test.yml
- .github/workflows/docker-build.yml
- .github/workflows/docker-sanity-test.yml
- .github/workflows/docker-smoke-test.yml
- .github/workflows/test-backstop.yml
- .github/workflows/test-docker.yml
@garris trying something else for the failing GH actions — I recently updated the `checkout` action to v4, and see that one of [their examples](https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit) uses `head.sha` instead of `head.ref`. 
Can we please give this a try?
> fix: use `github.event.pull_request.head.sha` for checkout@v4

- README.md
- core/util/runPlaywright.js
- core/util/runPuppet.js
- package.json
- test/configs/playwright.json
Puppeteer defaults to `"new"` headless mode, as per the feature request in #1525, also discussed in #1485. 
Playwright, on the other hand, will remain `headless: true` by default, as `"new"` mode is not supported without some configuration overhead. And speaking of Playwright...
> [!IMPORTANT]
> #1534 is fixed, which I found while exploring the above-mentioned caveats of `"new"` mode. 
> **This should be considered for an immediate patch**
In the end, we support `"new"` headless mode in Playwright, but only when set by a Backstop configuration file.
I also addressed a fix for GitHub Actions `npm run integration-test` error: `Error: Process completed with exit code 254.`.
Any and all input welcome! We want to be safe, but at the same time, want to support the cutting-edge and standards for …
> PATCH: Feature/1525 headless mode deprecation

- package-lock.json
- package.json
Chrome downloads changed their URLs: https://github.com/GoogleChromeLabs/chrome-for-testing/pull/108. This breaks Puppeteer installation until v22.1.0, which was updated to fetch from the new base URL: https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v22.1.0
Tested with `npm install` under this repo, it didn't work before this change and it works afterwards.
> fix: Upgrade Puppeteer to v22.1.0

- .github/workflows/dockerhub-build-push.yml
This adds a GitHub Workflow to build the multi-architecture Docker image, sign into Docker Hub, and push the image.
It uses the current `version` property in `package.json` as its tag, the same way `npm run build-and-publish` or `publish-docker` do.
1. Create a Docker Hub Access Token ([this link](https://hub.docker.com/settings/security?generateToken=true) will prompt you after login)
2. Add two Actions Secrets
3. `DOCKERHUB_TOKEN`
4. `DOCKERHUB_USERNAME`
Here's the [workflow in action](https://github.com/dgrebb/BackstopJS/actions/runs/8012164310/job/21886901809). It fails because my Docker Hub account is not owner of backstopjs. Not the build successes for [amd](https://github.com/dgrebb/BackstopJS/actions/runs/8012164310/job/21886901809#step:8:1198) as well as …
> feat: docker hub build/push action (#1546)

- capture/engine_scripts/puppet/clickAndHoverHelper.js
- core/util/runPuppet.js
- examples/Jenkins/Sample/backstop_data/engine_scripts/puppet/clickAndHoverHelper.js
- examples/responsiveDemo/backstop_data/engine_scripts/puppet/clickAndHoverHelper.js
- test/configs/backstop_data/engine_scripts/puppet/clickAndHoverHelper.js
Small fix to address #1553 
In puppeteer waitForTimeout was implemented this way:
```javascript
/**
* @deprecated Replace with `new Promise(r => setTimeout(r, milliseconds));`.
*
* Causes your script to wait for the given number of milliseconds.
*
* @remarks
* It's generally recommended to not wait for a number of seconds, but instead
* use {@link Frame.waitForSelector}, {@link Frame.waitForXPath} or
* {@link Frame.waitForFunction} to wait for exactly the conditions you want.
*
* @example
*
* Wait for 1 second:
*
* ```ts
* await frame.waitForTimeout(1000);
* ```
*
* @param milliseconds - the number of milliseconds to wait.
*/
async waitForTimeout(milliseconds: number): Promise<void> {
return await new Promise(resolve => {
setTimeout(resolve, milliseconds);
});
}
``` 
Therefore it should …
> Change puppeteer's waitForTimeout into direct setTimeout

- core/util/engineTools.js
As reported in #1555, `mismatchThreshold` was mistyped while introducing scenario config defaults in #1539.
@garris this PR fixes the error of my ways...
> fix: remove "`config`" from `mismatchThreshold` (#1555)

- core/util/engineTools.js
This fixes #1557, which I introduced when working on #1492. My bad!
> fix: `misMatchThreshold` and `requireSameDimensions` nullish coalescing (#1557)

- .github/workflows/dockerhub-build-push.yml
Adds the `:latest` tag to `backstopjs/backstopjs` during the Build & Push GitHub Actions.
Possibly closes #1578 :)
> fix(docker): add `:latest` as target during push (#1578)
