garris/BackstopJS

README.md

+ Changes all usage over bower over to npm.
+ Changes references to `./bower_components` to `./node_modules`.

Update README.md for NPM Install

---

capture/config.default.json

Used "Fomat: Javascript" command, made sure objects in array started and
ended on their own line and were indented one more.

Format Default Configs

---

README.md

+ scenarios instead of grabConfigs.
+ Formatting.
+ label instead of testName.
+ Simplify viewport object.

Update README.md to Match Recent Config Changes

---

gulp/tasks/echo.js
gulp/tasks/test.js

Added args array for holding arguments to pass to CasperJS/PhantomJS.
Concatenated tests and args array into a casperArgs array to pass to spawn(casperProcess).

Add HTTPS protocol option to CasperJS spawn task.

---

capture/genBitmaps.js

A simple way to override user agent by viewport declaration

Let's spoof user agent

---

capture/genBitmaps.js

Revert "Let's spoof user agent"

---

capture/config.default.json
capture/echoFiles.js
capture/genBitmaps.js
compare/index.html

I don't think this is the best way to do it, but it seems to work. I've kept a default so the tests don't fail if the variable doesn't exist.
#52

Initial implementation of threshold configuration, with fallback to 1.

---

gulp/tasks/start.js
package.json

I would suggest it as fix for https://github.com/garris/BackstopJS/issues/59.
Tested on Windows.

Fix start task on windows

---

compare/index.html

Fix inconsistent html tags

---

README.md

Pretty minor, but it's WordPress, not Wordpress.

WordPress has a capital P

---

test/onReadyScript/onReady.js

This should also help for #109. Is there anything else I'm missing for this test?

adding tests for #113

---

capture/casper_scripts/onBefore.js
capture/casper_scripts/onReady.js
capture/config.default.json
capture/genBitmaps.js

#147: added onBeforeScript; added option for global onBeforeScript/onReadyScript

---

README.md

The readme file is updated with the xunit report generation details

updated the README file with the xunit report generation details

---

gulp/tasks/compare.js

It is useful to see all the test-cases all the time irrespective of success/failure.

xunit testcase addition even for successcase

---

gulp/tasks/compare.js

Please find the bug details #214

test report file generation [Fixes #214]

---

capture/genBitmaps.js
test/login/backstop_data/casper_scripts/onBefore.js

This is a follow up PR to #220
Instead of mutating scenario object, let's add fourth argument to both onReady and onBeforeReady scripts.

Pass isReference value to onReady and onBeforeReady scripts

---

README.md
capture/config.default.json
capture/genBitmaps.js

Update typo's in README.md

---

core/util/createBitmaps.js

scenario filtering typo fix.

---

capture/genBitmaps.js
core/util/runCasper.js

Hello @garris 
This is my requested change for authentication via CLI.
It's npm conform and gives the optional parameters --user="" and --password=""
So in an automated flow we can auth several users via CLI.
Best,
Sven

CLI Authentification

---

capture/casper_scripts/onBefore.js
capture/casper_scripts/onReady.js
capture/genBitmaps.js
cli/index.js
cli/usage.js
core/command/approve.js
core/command/openReport.js
core/command/report.js
core/util/compare.js
core/util/createBitmaps.js
core/util/findExecutable.js
core/util/makeConfig.js
core/util/runCasper.js

Fix ESLint errors on „npm run lint-node“

---

README.md

minor documentation update to reflect awesome new defaults

Update Readme to signify Chromy being default

---

docker/Dockerfile
docker/hooks/build
docker/hooks/post_push

See https://github.com/garris/BackstopJS/issues/602#issuecomment-351777465
* Update Dockerfile and add the build hook to pass the version as
argument (extracted from the package.json file)
* Add the "post_push" hook (to generate the "latest" image)

Tagging docker images - #602

---

core/command/report.js

update junit report creating and prevent caching outdated test results

update junit report creating and prevent caching outdated test results

---

core/util/makeConfig.js

Actually showing the user config if detected in `options`.

Be more specific

---

examples/simpleReactApp/readme.md

There is no npm run test command.

Update test command for the react

---

core/command/approve.js

Solving issue with approve not returning Promise.
[Original issue](https://github.com/garris/BackstopJS/issues/441)

Promise support for backstops approve

---

core/util/runPuppet.js

* Add error images for Puppeteer selector capturing
* improve handling Puppeteer errors

Improve Puppeteer error handling

---

README.md

I thought it'd be good to change that example install command in troubleshooting, because a new dev might copy-and-paste that exact line and install the wrong package entirely. Also did some spellchecking.
Thanks!

README: Troubleshooting-- edit example command. Also some typo fixes.

---

README.md

Added Puppeteer to the features list in Readme

---

.travis.yml
README.md
capture/backstopTools.js
capture/engine_scripts/casper/clickAndHoverHelper.js
capture/engine_scripts/casper/onReady.js
capture/engine_scripts/puppet/clickAndHoverHelper.js
capture/engine_scripts/puppet/loadCookies.js
capture/genBitmaps.js
compare/src/components/App.js
compare/src/reducers/tests.js
compare/webpack.config.js
core/command/approve.js
core/util/createBitmaps.js
core/util/engineTools.js
core/util/getFreePorts.js
core/util/makeConfig.js
core/util/runChromy.js
core/util/runPuppet.js
package-lock.json
package.json

Fix open lint issues (addresses #741). Does not (yet) enable lint during travis build.

Fix lint issues

---

core/util/runPuppet.js

Should fix https://github.com/garris/BackstopJS/issues/752

Fix multiple hidden and removed selectors

---

compare/src/actions/index.js
compare/src/components/App.js
compare/src/components/atoms/ImageScrubber.js
compare/src/components/ecosystems/ScrubberModal.js
compare/src/reducers/scrubber.js
core/command/report.js

Hi @garris and @matthiaskomarek.
I have added this diff button as mentioned in #710 and it looks like this:
This is my first time touching a React project, so please bear with me if I missing something 🙂
I would like to get your feedback on it all, but also wether the -1 position makes sense or not for the diff button - suggestions are very welcome!
Thanks!

Adding diff button to ScrubberModal component (#710)

---

docker/Dockerfile

Maybe fixes #851? I'm not sure how to test this without creating a Docker Hub account and publishing an image there,

Upgrade Node version in Docker image

---

core/util/runDocker.js
docker/hooks/post_push

This way new Docker images won't break existing clients.
Closes #861

Pin client to specific Docker image version

---

.travis.yml

10 is the latest release and will be LTS soon.

Run tests against Nodejs 8 and 10

---

core/util/runDocker.js

- Handle `error` event
- Reject with an error so we preserve stack trace

Better Docker error handling

---

cli/index.js

Don't override mocha's exit code

---

package-lock.json
package.json

Puppeteer was in a version over 6 months ago. I was having a problem that the click on the element was not working properly.

Bump puppeteer

---

cli/index.js
package.json

Not just the ones in `test/cli`.

Run all tests in `unit-test` script

---

core/util/runDocker.js

Allow running `backstop --config file test --docker`

---

remote/index.js

Details here:
https://github.com/garris/ember-backstop/issues/8
Has a matching pull-request for ember-backstop.

Add configurable scenario options in dynamic tests

---

README.md

doc: fix one capitalisation error

---

test/core/command/report_spec.js
test/core/util/makeConfig_it_spec.js
test/core/util/makeConfig_spec.js

Fixed all unit tests.
It's a first step for #1006

fix unit tests

---

test/cli/index_spec.js

https://github.com/garris/BackstopJS/issues/1006

Temporarily skip cli test to fix CI

---

index.html

This avoids potential security issue with older version.
https://snyk.io/vuln/npm:jquery

Update jQuery to latest (v3.4.1)

---

README.md

I believe this should be "`reference URL property`".

Fix typo at `onBefore` section (propery => property)

---

core/util/runPuppet.js
package-lock.json
package.json

Docker BackstopJS sometimes produces white or cut-off screenshots

---

docker/Dockerfile

I think you need to combine your installs or it will try to install without souces/lists.

Clean up dockerfile.

---

core/util/runDocker.js

Desired for more advanced setups.

Enable multiple {cwd} in dockerCommandTemplate

---

README.md

So I migrated my blog away from heroku and connected to my actual domain. :)

Fix readme link to blog post

---

package-lock.json
package.json

Tried to use `inputFile.uploadFile` with the current puppeteer in use it doesn't work; but works with the latest one.

Upgrade puppeteer from 2.0.0 to 5.5.0

---

core/command/remote.js
package-lock.json
package.json

Closes #1315
Replaced `resolve` depency with `require.resolve()`

refactor: replaced resolve dependency with require.resolve()

---

README.md

It's kind of painful trying to watch your browser when 10s of popups keep spawning!

Document how to suppress firewall popups on macOS

---

README.md

Since the EN version has been unpublished.
Cc. @garris.

Update course links to the PT-BR version

---

docker/Dockerfile

@garris another PR for you to consider ;-) .

use shared playwright browser location path (#1468)

---

docker/Dockerfile

removed by accident with 6d221a275686bad7c7b58fd7ff1325e7067e1bcb

add back proper CJK font support (#1469)

---

core/util/engineTools.js

Make getRequireSameDimensions return either defaultRequireSameDimensions or true (instead of 0.1)

#1568 Fix defaults in getRequireSameDimensions
